on:
  push:
    branches:
      - main

env:
  BUN_VERSION: '1.1.32' # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install packages and build
        run: |
          bun install
          bun run build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Deploy
        id: deploy-to-server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: '.'
          target: /data/timecapsule

      - name: Run
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            PATH="/home/user/.bun/bin/:$PATH"
            cd /data/timecapsule
            rm -rf ./node_modules/
            bun i
            bun update-db
            pm2 delete timecapsule-app
            pm2 delete timecapsule-worker
            pm2 start --interpreter bun --name timecapsule-app ./build/index.js
            pm2 start --interpreter bun --name timecapsule-worker ./src/scripts/cron.ts
